[package]
name = "air-parser"
version = "0.1.0"
description="Parser for the AirScript language"
authors = ["miden contributors"]
readme="README.md"
license = "MIT"
repository = "https://github.com/0xPolygonMiden/air-script"
categories = ["compilers", "cryptography", "parser-implementations"]
keywords = ["air", "stark", "zero knowledge", "zkp"]
edition = "2021"
rust-version = "1.65"
[build-dependencies]
lalrpop = "0.19.7"

[dependencies]
lalrpop-util = { version = "0.19.7" }
logos = "0.12.0"
regex = "1"