[book]
authors = ["grjte"]
language = "en"
multilingual = false
src = "src"
title = "AirScript by Polygon Miden"

[output.katex]
[output.html]

[output.linkcheck]
warning-policy = "ignore"

[preprocessor.katex]
