[book]
authors = ["grjte"]
language = "en"
multilingual = false
src = "src"
title = "AirScript by Polygon Miden"

[output.html]
git-repository-url = "https://github.com/0xPolygonMiden/air-script/"

[preprocessor.katex]
after = ["links"]

[output.linkcheck]
warning-policy = "ignore"
