[book]
authors = ["miden contributors"]
language = "en"
multilingual = false
src = "src"
title = "AirScript by Miden"

[output.html]
git-repository-url = "https://github.com/0xMiden/air-script/"
mathjax-support = true

[preprocessor.katex]
after = ["links"]

[output.linkcheck]
warning-policy = "ignore"
