[package]
name = "air-script"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "airc"
path = "src/main.rs"

[dependencies]
parser = { package = "air-parser", path = "../parser", version = "0.1.0" }
ir = { package = "air-ir", path = "../ir", version = "0.1.0" }
codegen-winter = { package = "air-codegen-winter", path = "../codegen/winterfell", version = "0.1.0" }
structopt = "0.3.26"
env_logger = "0.9"
log = { version = "0.4", default-features = false }

[dev-dependencies]
expect-test = "1.4.0"
